version: '3'

services:
  bitwarden:
    image: bitwardenrs/server:latest #使用 bitwardenrs/server 最新镜像（2020年11月16日更新镜像地址，原镜像很久没更新有些小bug）
    container_name: bitwarden
    restart: always
    volumes:
      - ./bw-data:/data  #容器内的 /data 目录挂载到宿主机的当前目录下的 data 目录；
    ports:
      - "127.0.0.1:17080:80" #将容器内的 80 端口映射到了宿主机的 47878 端口；
      - "127.0.0.1:3012:3012"
    environment:
      - SIGNUPS_ALLOWED=false